version: '3.8'

services:
  bak_db:
    image: postgres:15
    container_name: bak_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - bak_postgres_data:/var/lib/postgresql/data
    networks:
      - bak_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  bak_cache:
    image: redis:latest
    container_name: bak_cache
    ports:
      - "6379:6379"
    volumes:
      - bak_redis_data:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    networks:
      - bak_net
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  bak_net:
    driver: bridge

volumes:
  bak_postgres_data:
  bak_redis_data:
